# Generated by Django 2.2.12 on 2020-11-16 14:20

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlerating_group', to='otree.Session')),
            ],
            options={
                'db_table': 'ArticleRating_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlerating_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'ArticleRating_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('ratingPreview1', otree.db.models.IntegerField(null=True)),
                ('ratingPreview2', otree.db.models.IntegerField(null=True)),
                ('ratingPreview3', otree.db.models.IntegerField(null=True)),
                ('ratingPreview4', otree.db.models.IntegerField(null=True)),
                ('ratingPreview5', otree.db.models.IntegerField(null=True)),
                ('ratingPreview6', otree.db.models.IntegerField(null=True)),
                ('ratingPreview7', otree.db.models.IntegerField(null=True)),
                ('ratingPreview8', otree.db.models.IntegerField(null=True)),
                ('ratingPreview9', otree.db.models.IntegerField(null=True)),
                ('ratingPreview10', otree.db.models.IntegerField(null=True)),
                ('ratingPreview11', otree.db.models.IntegerField(null=True)),
                ('ratingPreview12', otree.db.models.IntegerField(null=True)),
                ('ratingPreview13', otree.db.models.IntegerField(null=True)),
                ('ratingPreview14', otree.db.models.IntegerField(null=True)),
                ('ratingPreview15', otree.db.models.IntegerField(null=True)),
                ('ratingPreview16', otree.db.models.IntegerField(null=True)),
                ('ratingPreview17', otree.db.models.IntegerField(null=True)),
                ('ratingPreview18', otree.db.models.IntegerField(null=True)),
                ('ratingPreview19', otree.db.models.IntegerField(null=True)),
                ('ratingPreview20', otree.db.models.IntegerField(null=True)),
                ('ratingPreview21', otree.db.models.IntegerField(null=True)),
                ('ratingPreview22', otree.db.models.IntegerField(null=True)),
                ('ratingPreview23', otree.db.models.IntegerField(null=True)),
                ('ratingPreview24', otree.db.models.IntegerField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArticleRating.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlerating_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articlerating_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleRating.Subsession')),
            ],
            options={
                'db_table': 'ArticleRating_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleRating.Subsession'),
        ),
    ]
